
#ifndef CONSTANTES_H
#define CONSTANTES_H

// Constantes du dessin
#define CHAR_SPACE 0
#define CHAR_TOP_LEFT 1
#define CHAR_HORIZONTAL 2
#define CHAR_TOP_RIGHT 3
#define CHAR_BOTTOM_LEFT 4
#define CHAR_BOTTOM_RIGHT 5
#define CHAR_VERTICAL 6
#define CHAR_TOP_LEFT_DOUBLE 7
#define CHAR_HORIZONTAL_DOUBLE 8
#define CHAR_TOP_RIGHT_DOUBLE 9
#define CHAR_BOTTOM_RIGHT_DOUBLE 10
#define CHAR_BOTTOM_LEFT_DOUBLE 11
#define CHAR_VERTICAL_DOUBLE 12
#define CHAR_TOP_LEFT_TRIPLE 13
#define CHAR_HORIZONTAL_TRIPLE 14
#define CHAR_TOP_RIGHT_TRIPLE 15
#define CHAR_BOTTOM_RIGHT_TRIPLE 16
#define CHAR_BOTTOM_LEFT_TRIPLE 17
#define CHAR_VERTICAL_TRIPLE 18
#define CHAR_BLANK 19
#define CHAR_RIGHT_DOUBLE 20
#define CHAR_TOP_DOUBLE 21
#define CHAR_BOTTOM_DOUBLE 22
#define CHAR_NEW_LINE 23
#define CHAR_SLASH 24
#define CHAR_BACKSLASH 25
#define CHAR_SQUARE 26

#define BORDER_START_POSITION_X 0
#define BORDER_START_POSITION_Y 0
#define BORDER_END_POSITION_X 101
#define BORDER_END_POSITION_Y 26
#define BOX_2_START_POSITION_X 45
#define BOX_2_START_POSITION_Y 3
#define BOX_2_END_POSITION_X 20
#define BOX_2_END_POSITION_Y 98
#define BOX_1_START_POSITION_X 4
#define BOX_1_START_POSITION_Y 3
#define BOX_1_END_POSITION_X 20
#define BOX_1_END_POSITION_Y 30









#endif